### ISSUE TITLE
add config to remove "special tools"

### ISSUE THREAD

**Issue by memphismc** [kwpugh/emerald_tools_fabric#48]
basically, i want my game to be as vanilla as possible while still having emerald tools so i'd love a config to remove the special bows and tools and only have the respective vanilla emerald tools (no upgradable bows and no 3x3 tools etc.)

it would be cool if this was also a feature in gobber

**Comment by kwpugh** [comment]
this is not done through config.  once an item is registered in game, it should not be removed.   There are mods that allow you to remove items from tabs and recipes if you want that.
